### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by vjrj** [comunes/todos-contra-el-fuego-web#3]
https://sentry.comunes.org/comunes/todos-contra-el-fuego-dev/issues/443/

```
TypeError: Cannot read property 'bind' of undefined
  at new Feedback (/app/app.js:2748:45)
  at constructClassInstance (/packages/modules.js:28223:20)
  at updateClassComponent (/packages/modules.js:29707:9)
  at beginWork (/packages/modules.js:30093:16)
  at performUnitOfWork (/packages/modules.js:32092:16)
...
(18 additional frame(s) were not displayed)
```

**Comment by vjrj** [comment]
Solved long time ago
